version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_CONNECT: kafka:9092
    depends_on:
      - kafka

  eureka:
    build: ./eureka
    ports:
      - "8761:8761"

  authentication:
    build: ./authentication
    ports:
      - "8070:8070"
    depends_on:
      - eureka

  post:
    build: ./post
    ports:
      - "8090:8090"
    depends_on:
      - eureka

  messaging:
    build: ./messaging
    ports:
      - "8050:8050"
    depends_on:
      - eureka
      - kafka

  gateway:
    build: ./gateway
    ports:
      - "8222:8222"
    depends_on:
      - authentication
      - post
      - messaging
    environment:
      - SPRING_PROFILES_ACTIVE=docker
