eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true


server:
  port: 8050

spring:
  profiles:
    active: local
  application:
    name: messaging
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/messaging
    username: postgres
    password: hala123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.hala.messagerie.dto
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    springdoc:
    swagger-ui:
      path: /swagger-ui.html

urls:
  message: http://localhost:8050/api/v1/messages
  privateMessage: http://localhost:8050/api/private-messages
  groupMessage: http://localhost:8050/api/groupmessages
